### ISSUE TITLE
Windowsのスケーリングを使用している環境で「Area Select」の取り込み範囲がずれる

### ISSUE THREAD

**Issue by smallfish135** [Alalf/SCFF-DirectShow-Filter#109]
こんにちは。Windows 7 のスケーリング機能を使っている環境下では SCFF の「Area Select」の取り込み範囲がずれてしまうようです。（ずれる程度はスケーリングの量に比例？）
同一環境でもスケーリングをOFFにするとずれずに取り込めます。修正してくださるとありがたいです。

再現方法
スケーリングを有効にすると再現します。
スケーリングの設定方法
https://technet.microsoft.com/ja-jp/windows/win7_tips33.aspx

実行環境はWindows 7 64bitです。

**Comment by Alalf** [comment]
バグ報告ありがとうございます。修正しておきました。
